{
 "title": "Telegraf metrics monitoring template",
 "description": "A public dashboard for Telegraf metrics monitoring using Grafana",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heap Memory in use",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"Telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"internal_memstats\")\n  |> filter(fn: (r) => r._field == \"mallocs\")\n  |> derivative(unit: v.windowPeriod, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"Telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"internal_memstats\")\n  |> filter(fn: (r) => r._field == \"num_gc\")\n  |> derivative(unit: v.windowPeriod, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "Heap Memory in use",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"Telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"internal_memstats\")\n  |> filter(fn: (r) => r._field == \"heap_in_use_bytes\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  { "title": "Agent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Agent - Metrics Gathered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"internal_agent\")\n  |> filter(fn: (r) => r._field == \"metrics_gathered\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Agent - Metrics Written",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"internal_agent\")\n  |> filter(fn: (r) => r._field == \"metrics_written\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"internal_write\" or r._measurement == \"internal_agent\")\n  |> filter(fn: (r) => r._field == \"errors\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> derivative(unit: v.windowPeriod, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")"
    }
   ]
  },
  {
   "title": "Agent - Metrics Dropped",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental/aggregate\"\nimport \"experimental/query\"\nfrom(bucket: \"Telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"metrics_dropped\")\n  |> aggregate.rate(every: v.windowPeriod, unit: 1s)\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Agent - Metrics gathered vs written per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "import \"experimental/aggregate\"\nfrom(bucket: \"Telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"internal_agent\")\n  |> filter(fn: (r) => r._field == \"metrics_gathered\" or r._field == \"metrics_written\")\n  |> aggregate.rate(every: v.windowPeriod, unit: 1s, groupColumns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Agent - input plugin errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "query": "import \"experimental/aggregate\"\nfrom(bucket: \"Telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"internal_agent\")\n  |> filter(fn: (r) => r._field == \"gather_errors\")\n  |> group()\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(unit: v.windowPeriod, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")"
    }
   ]
  },
  {
   "title": "Agent - Metrics Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"Telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"internal_agent\")\n  |> filter(fn: (r) => r._field == \"metrics_dropped\")\n  |> group()\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(unit: v.windowPeriod, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")"
    }
   ]
  },
  { "title": "Input", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Inputs - metrics gathered per input per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "import \"experimental/aggregate\"\nfrom(bucket: \"Telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"internal_gather\")\n  |> filter(fn: (r) => r._field == \"metrics_gathered\")\n  |> derivative(unit: v.windowPeriod, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\n  |> aggregateWindow(every: duration(v: int(v: v.windowPeriod) * 6), fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Inputs - Errors per input",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "query": "import \"experimental/aggregate\"\nfrom(bucket: \"Telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"internal_gather\")\n  |> filter(fn: (r) => r._field == \"errors\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(unit: v.windowPeriod, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")"
    }
   ]
  },
  {
   "title": "Inputs - Time to gather metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"Telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"internal_gather\")\n  |> filter(fn: (r) => r._field == \"gather_time_ns\")\n  |> map(fn: (r) => ({ r with _value: r._value / 1000000 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)"
    }
   ]
  },
  { "title": "Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Output - Write buffer size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"Telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"internal_write\")\n  |> filter(fn: (r) => r._field == \"buffer_size\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Output - Errors per output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "query": "import \"experimental/aggregate\"\nfrom(bucket: \"Telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"internal_write\")\n  |> filter(fn: (r) => r._field == \"errors\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> derivative(unit: v.windowPeriod, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")"
    }
   ]
  },
  {
   "title": "Outputs - Write time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "query": "import \"date\"\nfrom(bucket: \"Telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"internal_write\")\n  |> filter(fn: (r) => r._field == \"write_time_ns\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)"
    }
   ]
  }
 ]
}